### PR TITLE
Fix RFC1123 formating in Last-Modified header

### LINKED ISSUE #78: Last-Modified in bootstrap.php incorrectly formatted
Please see https://drupal.org/node/1918820

Recommendation: use gm_date('D, d M Y H:i:s').' GMT'

We had to patch it for proper proxying.

### PR DESCRIPTION
**Pull request by neclimdul**
Fixes #78

### CODE REVIEW

**Comment by achton** [comment]
+1 for this cleanup. This has been fixed in D7 since Nov 2014.

**Comment by pwolanin** [comment]
Drupal 6 core has e.g.

```
  header("Last-Modified: ". gmdate("D, d M Y H:i:s") ." GMT");
```
Though I agree the formatting doesn't really matter.

I'm also curious why this is using ```REQUEST_TIME``` - that's just an optimization to avoid calling out to ```time()```?

**Comment by achton** [comment]
I guess the `$_SERVER['REQUEST_TIME']` part is another backport from D7, although it's really `(int) $_SERVER['REQUEST_TIME']`. 
No idea if PHP is *really* calling time() if you omit the 2nd argument, or if it has access to some internal pointer which directly gives you the time() value.
I guess there could be slight difference between the value of time() and REQUEST_TIME as well.
In any case, it can't make a huge difference, methinks.

**Comment by neclimdul** [comment]
Probably. We got strict about this in Drupal 7 and I assume David was following that here 586e6d9 when he added it.

**Comment by neclimdul** [comment]
I can't see a reason for this to still be open :)

**Pull request closed without merging**
