### PR TITLE
SA-CORE-2016-001 (updates 6.37 to 6.38)

### PR DESCRIPTION
**Pull request by dsnopek**
A first pass at re-rolling the changes from https://www.drupal.org/SA-CORE-2016-001 for Pressflow!

### CODE REVIEW

**Comment by fluxsauce** [comment]
Any objections to consolidating on the existing PR - https://github.com/pressflow/6/pull/101 ?

**Comment by dsnopek** [comment]
Ah, sorry, I just didn't see that one. :-) I did the common.inc changes differently, so I put how I did them in the comments. I'm fine closing this one and continuing there!

**Comment by dsnopek** [comment]
Temporarily re-opening until #101 comes back to life! :-)

**Comment by dsnopek** [comment]
#101 has my changes! Closing again.

**Pull request closed without merging**
