### PR TITLE
Backport of fixes from SA-CORE-2018-002

### PR DESCRIPTION
**Pull request by dsnopek**
I think I now have permission to merge to upstream Pressflow, but I actually don't know the process for creating Pressflow releases yet!

@mparker17 or @pwolanin or anyone else: is this something you could help out with?

Otherwise, I'll look into it and give it a shot later...

### CODE REVIEW

**Comment by mparker17** [comment]
Looks good to me.

**Comment by pwolanin** [comment]
Taking a look - I see a merge button

**Comment by pwolanin** [comment]
Our prior release says 6.39, so version number looks right
https://github.com/pressflow/6/releases/tag/pressflow-6.39.122

**Comment by FGM** [comment]
Code-complete, but misses the CHANGELOG.txt update.

**Comment by Ishino** [comment]
thanks for the effort on this @dsnopek !

**Comment by pwolanin** [comment]
@FGM we can add that in and bump just the pressflow part of the version if you think it is useful

**Pull request merged**
