### PR TITLE
Backport of fixes for SA-CORE-2018-001

### PR DESCRIPTION
**Pull request by dsnopek**
See https://www.mydropwizard.com/blog/drupal-core-security-update-sa-core-2018-001-including-drupal-6

### CODE REVIEW

**Comment by dsnopek** [comment]
@pwolanin @fluxsauce Any chance of this one getting merged?

In our vanilla Drupal 6 fork, we incremented the version number to [6.41](https://github.com/d6lts/drupal/releases/tag/6.41) which I didn't do here because I don't know how Pressflow wants to handle version numbers.

Thanks!

**Comment by pwolanin** [comment]
@dsnopek  how did you get up to 6.41?  

We should probably increment the version here.

**Comment by dsnopek** [comment]
> @dsnopek how did you get up to 6.41?

Bug fixes after testing on live customer sites :-) We haven't gotten any new issues reported in over 24 hours. We could wait a little longer to see if more come in, so Pressflow doesn't end up doing any bug fix releases? But that's up to the maintainers, depending how to balance getting the security fix out versus potential regressions

> We should probably increment the version here.

Ok! To what version? 6.41 to match the vanilla release? Or 6.39 so their aren't skipped versions?

**Comment by pwolanin** [comment]
Are there other fixes we should pull into pressflow?

**Comment by dsnopek** [comment]
This PR is up-to-date with the latest patch for SA-CORE-2018-001 - through the magic of `git commit --amend` the commit has an old timestamp.

We don't have any other core patches. I saw that catch is working on a security hardening thing [here](https://www.drupal.org/project/d6lts/issues/2946893), which would probably be good to get into Pressflow eventually, but I don't know how that's going.

**Comment by pwolanin** [comment]
Let's go to 6.39 here

**Comment by dsnopek** [comment]
Version updated!

**Comment by pwolanin** [comment]
release: https://github.com/pressflow/6/releases/tag/pressflow-6.39.122

**Pull request merged**
