### PR TITLE
Apply the changes from D6LTS 6.45

### PR DESCRIPTION
**Pull request by dsnopek**
So, Drupal 6.45 was released to add PHP 7 support. Unfortunately, we haven't had a chance to really test PHP 7 with Pressflow 6. But here's the same changes applied to Pressflow, which at the very least shouldn't be harmful, and will help to keep the version numbers in sync.

### CODE REVIEW

**Comment by pwolanin** [comment]
This should maintain PHP 5 compatibility?

**Comment by pwolanin** [comment]
@dsnopek  the change set looks pretty reasonable to me and not very risky.  You have not had problems with the LTS and this?

**Comment by dsnopek** [comment]
This is in use on customer sites for over a month now, and we haven't had an complaints. :-)

**Comment by snpdev** [comment]
Thanks @pwolanin  and @dsnopek. Is a release 6.46 imminent?

FWIW, we run two Pressflow 6 sites on PHP 5.6.21 with no issues.

**Comment by pwolanin** [comment]
draft release:
https://github.com/pressflow/6/releases/tag/untagged-3edf9f829738360c6972

Would be helpful if you can confirm master installs and/or updates cleanly
for you.

**Comment by snpdev** [comment]
@pwolanin, I have tested a site update from the latest master branch. No problems detected.

**Pull request merged**
